spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    properties:
      spring.json.value.default.type: com.example.notificationservice.model.OrderMessage
  # You can configure other services like an email service or SMS service here
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: user
    password: pass
    protocol: smtp
    from: notifications@example.com

server:
  port: 8083

# Logging configuration (optional)
logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.web: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  tracing:
    sampling:
      probability: 1.0